### ISSUE TITLE
Any other languages support?

### ISSUE THREAD

**Issue by remedge** [simara-svatopluk/ddd-course#2]
Apparently, this is a great course! Is there any way to translate it into other languages, such as English? :)

**Comment by remedge** [comment]
My mistake, I found the materials in English, sorry (:

https://github.com/simara-svatopluk/ddd-course/blob/master/1-overview/overview.md
https://github.com/simara-svatopluk/ddd-course/blob/master/2-language/language.md
https://github.com/simara-svatopluk/ddd-course/blob/master/3-model/model.md
https://github.com/simara-svatopluk/ddd-course/blob/master/4-implementation/implementation.md
https://github.com/simara-svatopluk/ddd-course/blob/master/5-persistence/persistence.md

**Comment by simara-svatopluk** [comment]
That was quick... good idea anyway. I'll add english summary as a first paragraph.

**Comment by simara-svatopluk** [comment]
@remedge https://github.com/simara-svatopluk/ddd-course Better? ;-)

**Comment by remedge** [comment]
@simara-svatopluk better than nothing :) Thank you!
